function dpow=calcdispow(modsimf, iclass, varname)
% calculate SIMCA discirminant Power for each variable
% starting from model generated by simca_fede
% dpow=calcdispow_tocorrect(modsimf, iclass,varname)
%% INPUT
% modsimf :   simca models for calibration
% iclass: vector holding class membership
% varname: variables label (could be omitted)
nc=modsimf.finalmodel.SIMCA.nclass;
M=size(modsimf.finalmodel.PCmodels{1}.res,2);
s2in=0;
s2not=0;
for ic=1:nc
    iin=find(iclass==ic);
    inot=find(iclass ~=ic);
    q=(modsimf.finalmodel.PCmodels{ic}.res).^2;    % holds the square residual from the model of class ic
    A=modsimf.finalmodel.SIMCA.ncomp(ic);
    s2in=(M/(M-A)).*(s2in + misssum(q(iin,:),1)./length(iin));
    s2not=(M/(M-A)).*(s2not + misssum(q(inot,:),1)./length(inot));
end
dpow=sqrt(s2not./s2in) -1;
figure;bar(dpow);
hold on;hline(prctile(dpow,95),'g');
hold on;hline(prctile(dpow,99),'r');
hold on;hline(mean(dpow),'k:');
legend({'Discriminant Power' '95 percentile' '99 percentile' 'average'})
if exist('varname')==1
    a=gca;
     a.XTickLabel=varname;
end
hgsave('dpow.fig');


